JoinColony/colonySDK

README.md
This just adds a bit more detail to README.md
=> Expand the README.md

packages/colony-starter-basic/package.json, packages/colony-starter-basic/src/__tests__/rinkeby.test.js, packages/colony-starter-basic/src/examples/connectRinkeby.js, packages/colony-starter-basic/src/rinkeby.js
Add `connectRinkeby` example and test to `colony-starter-basic` package
**Added Scripts**:
`src/rinkeby.js`
#10
=> Add connectRinkeby example and test

packages/colony-starter-basic/package.json, packages/colony-starter-basic/src/examples/connectMetamask.js, packages/colony-starter-basic/src/metamask.js, yarn.lock
Add `connectMetamask` example to `colony-starter-basic` package
**Added Scripts**:
`src/metamask.js`
**Added Dependencies**:
```
"node-metamask": "^1.1.0",
"web3": "^1.0.0-beta.35"
```
#11
=> Add connectMetamask example

packages/colony-starter-basic/scripts/initialize_project.sh, packages/colony-starter-react/scripts/initialize_project.sh
Add `.gitignore` when running the initialize project script.
=> Add gitignore on initialize project

.circleci/config.yml, .github/DEVELOPMENT.md, README.md, docs/_Docs_Overview.md, docs/_Packages_ColonyStarter.md, docs/_Packages_ColonyStarterBasic.md, package.json, packages/colony-starter-basic/.circleci/config.yml, packages/colony-starter-basic/README.md, packages/colony-starter-basic/package.json, packages/colony-starter-basic/scripts/initialize_project.sh, packages/colony-starter-react/.circleci/config.yml, packages/colony-starter-react/README.md, packages/colony-starter-react/package.json, packages/colony-starter/package.json, yarn.lock
Updates to node version 9.10 in order to work with eslint configuration and adds docker pull image in order to deploy latest colonyNetwork contracts.
**Updated Scripts**:
_colony-starter-basic_
```
initialize_project.sh
```
=> Update node version and add docker pull

.circleci/config.yml, packages/colony-starter-basic/package.json, packages/colony-starter-basic/scripts/initialize_project.sh, packages/colony-starter-react/package.json, scripts/postinstall.sh
* Add checkout commit to postinstall script
* Use commit associated with latest Rinkeby deployment
* Update `@colony/colony-js-network-loader` package
**Updated Scripts**:
_colony-starter-basic_:
```
initialize_project.sh
```
=> Update network commit and pull docker image

.github/DEVELOPMENT.md, .github/LINUX_SETUP.md, README.md, docs/_Docs_Overview.md, docs/_Packages_ColonyStarter.md, docs/_Packages_ColonyStarterBasic.md, packages/colony-starter-basic/README.md, packages/colony-starter-react/README.md
Adds linux-specific setup instructions to workaround the errors with docker and global yarn commands.
=> Add document and link for linux setup

README.md
This pull request updates the CircleCI badge, adds a Gitter badge for the colonyStarter channel, and decreases the number of Discourse badges.
This pull request also deceases the width of the banner image and centers it.
=> Update readme badges and svg banner

README.md
Just some extra instructions to speed up the colony-starter setup
=> Added 1-step install for colony-starter-basic

.github/DEVELOPMENT.md, README.md, docs/_Docs_Overview.md, docs/_Packages_ColonyStarter.md, docs/_Packages_ColonyStarterBasic.md, packages/colony-starter-basic/README.md, packages/colony-starter-react/README.md
Add recommended yarn version to documentation
Related to #45
=> Add recommended yarn version to documentation

packages/colony-starter-react/src/client/containers/Manage/Tasks/CreateTask.jsx
Fix `handleChange` for task `domainId`.
=> Fix `handleChange` for task `domainId`

docs/_Docs_Overview.md
This pull request fixes the links at the bottom of the overview page.
=> Fix overview contribute links in docs

packages/colony-starter-angular/package.json, packages/colony-starter-angular/src/app/app.component.html, packages/colony-starter-angular/src/app/app.component.ts, packages/colony-starter-angular/src/app/app.module.ts, packages/colony-starter-angular/src/app/app.service.ts, packages/colony-starter-angular/src/styles.css, yarn.lock
Added front end UI using Angular Material.
Refactored code to use a service to execute Colony code, rather than have it run in the component. This improves modularity.
I didn't have any errors, but would be good to get a second set of eyes on it.
**Added Dependencies**:
[Angular Material](https://material.angular.io)
See [issue 59](https://github.com/JoinColony/colonyStarter/issues/59).
=> Add UI to colony-starter-angular

docs/_Packages_ColonyStarterBasic.md, docs/_Packages_ColonyStarterReact.md, packages/colony-starter-basic/README.md
This pull request updates the links to the colonyJS documentation.
Related to JoinColony/colonyJS#348
=> Update links to colonyJS documentation

.gitmodules, packages/colony-starter-angular/scripts/deploy_contracts.sh, packages/colony-starter-angular/scripts/initialize_project.sh, packages/colony-starter-angular/scripts/start_ganache.sh, packages/colony-starter-angular/scripts/start_trufflepig.sh, packages/colony-starter-basic/scripts/deploy_contracts.sh, packages/colony-starter-basic/scripts/initialize_project.sh, packages/colony-starter-basic/scripts/start_ganache.sh, packages/colony-starter-basic/scripts/start_trufflepig.sh, packages/colony-starter-react/scripts/deploy_contracts.sh, packages/colony-starter-react/scripts/initialize_project.sh, packages/colony-starter-react/scripts/start_ganache.sh, packages/colony-starter-react/scripts/start_trufflepig.sh, scripts/deploy_contracts.sh, scripts/postinstall.sh, scripts/start_ganache.sh, scripts/start_trufflepig.sh
This pull request updates the path to the colonyNetwork submodule in the root directory:
`modules/colonyNetwork` -> `lib/colonyNetwork`
As well as the path to the colonyNetwork submodule in each of the packages:
`src/lib/colonyNetwork` -> `lib/colonyNetwork`
=> Update path to colonyNetwork submodule

packages/colony-starter-basic/package.json, packages/colony-starter-basic/src/examples/revealTaskWorkRating.js, packages/colony-starter-basic/src/examples/submitTaskWorkRating.js, packages/colony-starter-react/package.json, packages/colony-starter-react/src/helpers/actions/taskActions.js, packages/colony-starter-react/src/helpers/actions/tokenActions.js, yarn.lock
This pull request adds `web3-utils` as a dependency and replaces the use of `web3.utils`.
_List any added/updated dependencies._
**Added Dependencies**:
```
"web3-utils": "^1.0.0-beta.44"
```
=> Add web3Utils and replace use of web3.utils

README.md, docs/_Docs_Overview.md, packages/colony-example-angular/README.md, packages/colony-example-react/README.md, packages/colony-example/README.md, packages/colony-starter-angular/README.md, packages/colony-starter-react/README.md, packages/colony-starter/README.md
This pull request adds the necessary `pull docker image` step to the "Using NPX" instructions.
Closes #50
=> Add pull docker image to npx instructions

.circleci/config.yml, packages/colony-cli/src/actions/build.js, packages/colony-cli/src/index.js, scripts/colony.js
This pull request adds support for `truffle` options by allowing unknown options to be passed to the `service` action within the `colony-cli` package.
=> Allow unknown options with service action

.eslintrc, README.md, docs/reference/api/README.md, docs/reference/api/modules.md, docs/reference/api/modules/graph.md, examples/node/basic.ts, examples/node/graph-subscription.ts, examples/node/graph.ts, examples/node/index.ts, package-lock.json, package.json, src/graph/index.ts, typedoc.json
Yes, yes, we're bringing support for the Colony Subgraph to Colony SDK!
You can already explore the subgraph here:
https://thegraph.com/hosted-service/subgraph/joincolony/colony-xdai?query=Latest%2010
=> Colony Subgraph support

examples/browser/src/motions.ts, examples/browser/web/index.html, examples/browser/web/motions.html, src/ColonyNetwork/VotingReputation.ts
=> Add xdai motion example

docs/api/README.md, docs/api/classes/Colony.md, docs/api/classes/ColonyNetwork.md, docs/api/classes/OneTxPayment.md, docs/api/classes/VotingReputation.md, src/ColonyNetwork/Colony.ts, src/ColonyNetwork/ColonyNetwork.ts, src/ColonyNetwork/OneTxPayment.ts, src/ColonyNetwork/VotingReputation.ts, src/TxCreator/ColonyTxCreator.ts, src/constants.ts, src/ipfs/IpfsMetadata.ts
Adds some functions that Colony SDK was missing to achieve dApp feature-parity.
=> Add missing dapp functions

examples/node/automation.ts, src/ColonyNetwork/Colony.ts, src/TxCreator/TxCreator.ts
This PR fixes a few bugs and adds missing features. Namely:
- Protect against non-parseble logs from metaTx broadcaster
- Protect against non-existing domains when moving funds
=> Various bugfixes and implementation of missing features
